// import type { Metadata } from "next";
// import { Inter } from 'next/font/google';
// import '../globals.css';
// import { cn } from "@/lib/utils";
// import  Sidebar  from "@/components/Sidebar";
// // import SideNavbar from "@/components/SideNavbar"; // Make sure to import the SideNavbar component

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Dashboard Admin',
//     description: 'Ini adalah dashboard admin',
// };

// export default function RootLayout({
//     children
// }: {
//     children: React.ReactNode
// }) {
//     return (
//         <div className={cn(
//             "min-h-screen w-full bg-white text-black flex",
//             inter.className,
//             {
//                 "debug-screens": process.env.NODE_ENV === "development"
//             }
//         )}>
//             {/* sidebar */}
//             {/* <p className="border">Sidebar</p> */}
//             <Sidebar/>
//             {/* <SideNavbar /> */}
//             {/* main page */}
//             <div className="w-full p-8">{children}</div>
//         </div>
//     );
// }
"use client";
import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/admin/sidebar";
import Header from "@/components/admin/header";
import PageWrapper from "@/components/admin/pageWrapper";
import { useState } from "react";
import { ThemeProvider } from "@/components/ui/themeProvider";

const karla = Karla({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-karla",
});

// export const metadata: Metadata = {
//   title: "Admin Dashboard",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={karla.className}>
      <div className="light">
        <Sidebar />
         <ThemeProvider
            attribute="class"
            defaultTheme=""
            enableSystem
            disableTransitionOnChange
          >
        <div className="flex flex-col h-full w-full">
        <Header />
          <PageWrapper children={children} />
        </div>
        </ThemeProvider>
      </div>
    </div>
  );
}
